### ISSUE TITLE
I can't go backward in the mission state machine

### ISSUE THREAD

**Issue by gmassanek** [keep-delivering/com#20]
If I accidentally click the button to start a mission, there's no going back. I think both Theron and I have done it now.

**Comment by stevenweber** [comment]
Back to the homepage?

**Comment by stevenweber** [comment]
Ah, I think you're talking about starting tasks, and yeah, we definitely need to change that -- please don't accidentally start [this one](http://keepdelivering.herokuapp.com/missions/2a4210f8-1d88-4deb-a458-998bc28aae32/deliverables/1cb0a689-d862-471b-b6aa-b9ae382d3db0/requirements/118e1e26-1802-4505-ab32-88822b2f4d38/edit). Closing this as we can track it in KD.
